name: Updoc

on:
  workflow_dispatch:
    inputs:
      provider:
        description: 'The name of the provider, e.g. provider-aws'
        required: true
        type: string
      version:
        description: 'The version you would like the release to have, e.g. v0.1.0'
        required: true
        type: string

jobs:
  updoc:
    uses: turkenf/uptest/.github/workflows/updoc.yml@main
    secrets:
      UPBOUND_CI_PROD_BUCKET_SA: ${{ secrets.UPBOUND_CI_PROD_BUCKET_SA }}
    with:
      version: ${{ github.event.inputs.version }}
      provider: ${{ github.event.inputs.provider }}
